[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@forge=lib/forge-std/src/",
    "@openzeppelin=lib/openzeppelin-contracts/contracts/"
]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
